Start refactor of wan_monitor Use libraries to detect wan interface

diff --git a/attitude_adjustment/target/linux/armadaxp/base-files/usr/sbin/wan_monitor b/attitude_adjustment/target/linux/armadaxp/base-files/usr/sbin/wan_monitor
--- a/attitude_adjustment/target/linux/armadaxp/base-files/usr/sbin/wan_monitor
+++ b/attitude_adjustment/target/linux/armadaxp/base-files/usr/sbin/wan_monitor
@@ -1,7 +1,11 @@
 #!/bin/sh
+. /lib/functions.sh
+. /lib/functions/network.sh
 
-START=0
-WANPORT=/sys/class/neta-switch/port4/carrier
+local scriptname wanhasip wanport
+scriptname="$(basename $0)"
+wanhasip=0
+wanport=/sys/class/neta-switch/port4/carrier
 DELAY=2
 
 CNT_CONN=0
@@ -11,6 +15,10 @@ LINKPING=heartbeat.belkin.com
 PING_TIMEOUT=5000 #5s
 
 OUTLOG=/tmp/wan_log
+
+log_message() {
+	/usr/bin/logger "$scriptname: $1"
+}
 
 blinking_amber() {
 	/usr/sbin/ledctrl wan_amber 255 500 500
@@ -28,44 +36,40 @@ wan_white() {
 	/usr/sbin/ledctrl wan_white $1
 }
 
-WAN_IF=eth1
 obtain_wan_ip() {
-	while true
+	local wanif wanipaddr
+	while ! network_find_wan wanif
 	do
-		#echo "obtain_wan_ip"
-		wanip=`ifconfig $WAN_IF | awk -F':' '/inet addr/&&!/127.0.0.1/{split($2,_," ");print _[1]}'`
-	
-		if [ -z $wanip ]	# WAN IP address is NULL
-		then
-			wan_amber on
-			/usr/bin/logger "Get WAN IP address..."
-			sleep 1
-		else
-			#echo $wanip
-			START=1
-			break
-		fi	
+		log_message "Waiting for netifd to register wan interface"
+		sleep 2
 	done
+	while ! network_get_ipaddr wanipaddr "$wanif"
+	do
+		wan_amber on
+		log_message "Obtaining IP address on if: $wanif"
+		sleep 2	
+	done
+	wanhasip=1
 }
 
 conn_type_dynamic() {
 
 	#echo "conn_type_dynamic"
 
-	if [ $START -eq 0 ]; then 
+	if [ $wanhasip -eq 0 ]; then 
 		wan_amber off
 		wan_white off
 		obtain_wan_ip
 	fi
 
-	if [ $START -eq 1 ]; then
+	if [ $wanhasip -eq 1 ]; then
 		/bin/ping $LINKPING -c 3 -w ${PING_TIMEOUT} > $OUTLOG
 		ping_status=$?
 		if [ $ping_status -ne 0 ]
 		then
 			wan_amber on
 			#echo "PING FAILED:" $LINKPING $ping_status
-			/usr/bin/logger "PING FAILED"
+			log_message "PING FAILED"
 		else
 			wan_white on
 			#echo "PING OK:" $LINKPING $ping_status
@@ -73,24 +77,25 @@ conn_type_dynamic() {
 	fi
 }
 
+#FIXME: would hotplug better serve us here?
 echo "WAN LED MONITOR"
 while true
 do
-	x=`cat $WANPORT`
+	x=`cat $wanport`
 	#echo "Wan physical status" $x
 
 	#echo $CNT_CONN
 	if [ $x = "Up" ]; then
-		if [ $START -eq 0 -o $CNT_CONN -gt $DELAY_CONN ]; then
+		if [ $wanhasip -eq 0 -o $CNT_CONN -gt $DELAY_CONN ]; then
 			conn_type_dynamic
 			CNT_CONN=0
 		fi
 	elif [ $x = "Down" ]; then
-		/usr/bin/logger "No physical WAN cable"
+		log_message "No physical WAN cable"
 		wan_amber off
 		wan_white off
 		blinking_amber 
-		START=0
+		wanhasip=0
 		CNT_CONN=0
 	fi
 	CNT_CONN=$((CNT_CONN+1))
